### ISSUE TITLE
Rol bazlı kullanıcı yapısının oluşturulması

### ISSUE THREAD

**Issue by ackepenek** [ozgebarbaros/helpdesk#1]
Rol bazlı kullanıcı yapısıyla, bazı kullanıcılar ticket acabilecek, bazı kullanıcılar ticket statusunu degistirebilecek, ticket'İ bir baska kullanıcıya atayabilecek.

**Comment by ozgebarbaros** [comment]
Oluşturuldu. Ldap kullanıcıları ile django User modeli iliskilendirildi.
