### ISSUE TITLE
Dashboard sayfasının oluşturulması/düzenlenmesi

### ISSUE THREAD

**Issue by ackepenek** [ozgebarbaros/helpdesk#3]
Dashboard sayfasıyla kullanıcı açtığı ticketları statusu ile birlikte görebilecektir. Hem Ticket detay sayfasına gidilecek link yeni ticket olusturabilecek link olacaktır. (bu konusulabilir)

**Comment by ozgebarbaros** [comment]
commit db6a6de7fddc3ad5c5ee4ed9fd18b547996f7e14
